import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./ui/Sidebar";
import Navbar from "./ui/Navbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="flex flex-row min-h-screen">
          <Sidebar />

          <div className="flex-1 flex flex-col bg-slate-950">
            <Navbar />
            <main className="flex-1 p-6">
              <div className="">{children}</div>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
